In [1]:
import gym
import numpy as np
import time

from IPython.display import clear_output

In [2]:
env = gym.make('FrozenLake-v0', is_slippery=True)
env.reset()

0

In [3]:
env.render()


SFFF
FHFH
FFFH
HFFG


In [4]:
print(env.observation_space.n)
print(env.action_space.n)

16
4


In [5]:
env.reset()

while True:
    action = np.random.randint(0, 4)
    observation, reward, done, info = env.step(action)
    env.render()
    print('observation:', observation)
    print('reward:', reward)
    print('done:', done)
    print('info:', info)
    if done:
        break

env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
observation: 4
reward: 0.0
done: False
info: {'prob': 0.3333333333333333}
  (Right)
SFFF
FHFH
FFFH
HFFG
observation: 8
reward: 0.0
done: False
info: {'prob': 0.3333333333333333}
  (Up)
SFFF
FHFH
FFFH
HFFG
observation: 8
reward: 0.0
done: False
info: {'prob': 0.3333333333333333}
  (Up)
SFFF
FHFH
FFFH
HFFG
observation: 8
reward: 0.0
done: False
info: {'prob': 0.3333333333333333}
  (Right)
SFFF
FHFH
FFFH
HFFG
observation: 9
reward: 0.0
done: False
info: {'prob': 0.3333333333333333}
  (Left)
SFFF
FHFH
FFFH
HFFG
observation: 13
reward: 0.0
done: False
info: {'prob': 0.3333333333333333}
  (Up)
SFFF
FHFH
FFFH
HFFG
observation: 9
reward: 0.0
done: False
info: {'prob': 0.3333333333333333}
  (Up)
SFFF
FHFH
FFFH
HFFG
observation: 10
reward: 0.0
done: False
info: {'prob': 0.3333333333333333}
  (Down)
SFFF
FHFH
FFFH
HFFG
observation: 11
reward: 0.0
done: True
info: {'prob': 0.3333333333333333}


In [6]:
q_table = np.zeros([env.observation_space.n, env.action_space.n])
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
episodes = 5000
learning_rate = 0.03
discount = 0.9

done = False

for episode in range(episodes):
    state = env.reset()
    
    while True:
        action = np.argmax(q_table[state, :] + np.random.randn(1, 4))
        new_state, reward, done, info = env.step(action)
        q_table[state, action] = (1 - learning_rate) * q_table[state, action] + learning_rate * (reward + discount * np.max(q_table[new_state, :]))
        state = new_state
        
        if done:
            break        

In [8]:
env.reset()
env.render()

print('np.argmax:', np.argmax(q_table, axis=1))
print('np.around', np.around(q_table, 6))


SFFF
FHFH
FFFH
HFFG
np.argmax: [1 3 0 3 0 0 0 0 2 1 1 0 0 2 1 0]
np.around [[0.019969 0.02022  0.01985  0.018249]
 [0.012562 0.016511 0.015722 0.021249]
 [0.03118  0.027749 0.029917 0.01848 ]
 [0.01226  0.010771 0.008161 0.015418]
 [0.027105 0.018118 0.020492 0.011667]
 [0.       0.       0.       0.      ]
 [0.057844 0.036524 0.041582 0.007468]
 [0.       0.       0.       0.      ]
 [0.018903 0.040991 0.043734 0.042816]
 [0.047592 0.091284 0.088977 0.049129]
 [0.127887 0.161828 0.156688 0.026427]
 [0.       0.       0.       0.      ]
 [0.       0.       0.       0.      ]
 [0.044166 0.132841 0.159771 0.079307]
 [0.132958 0.465988 0.390315 0.452926]
 [0.       0.       0.       0.      ]]


In [9]:
episodes = 10
max_steps = 200
won = 0

for episode in range(episodes):
    clear_output(wait=True)
    state = env.reset()
    done = False
    
    for step in range(max_steps):
        clear_output(wait=True)
        
        action = np.argmax(q_table[state])
        new_state, reward, done, _ = env.step(action)
        print("*" * 10)
        print(f"Episode: {episode+1}")
        print(f"Step {step+1}")
        print(f"Result {won}/{episode}")
        env.render()
        time.sleep(0.2)
        state = new_state
        
        if reward:
            won += 1
            print("You reached the goal")
            break
        
        if done and not reward:
            print("You fell in the hole")
            break
        
    else:
        print(f"Maximum step ({max_steps}) limit reached.")
        
    time.sleep(2)
#     clear_output(wait=True)

print(f"Percentage of winning is {(won / episodes) * 100}%")
env.close()

**********
Episode: 10
Step 22
Result 2/9
  (Down)
SFFF
FHFH
FFFH
HFFG
You fell in the hole
Percentage of winning is 20.0%
