In [1]:
import tensorflow as tf
import numpy as np

In [15]:
print(tf.__version__)

1.12.0


In [3]:
# Inputs

height = tf.get_variable(name="height", dtype=tf.int32, initializer=tf.constant(5))
width = tf.get_variable(name="width", dtype=tf.int32, initializer=tf.constant(10))

print(height)
print(width)

<tf.Variable 'height:0' shape=() dtype=int32_ref>
<tf.Variable 'width:0' shape=() dtype=int32_ref>


In [4]:
area = tf.multiply(height, width)
print(area)

Tensor("Mul:0", shape=(), dtype=int32)


In [5]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(area)
    writer = tf.summary.FileWriter("logs", sess.graph)
    print(result)

50


In [9]:
def add_two_tensors(x, y, name="add1"):
    with tf.variable_scope(name):
        x = tf.get_variable(name=str(x), initializer=tf.constant(x))
        y = tf.get_variable(name=str(y), initializer=tf.constant(y))
        add = tf.add(x, y)
    return add

In [14]:
tf.reset_default_graph()

with tf.Session() as sess:
    result = add_two_tensors(10, 2)
    sess.run(tf.global_variables_initializer())
    result = sess.run(result)
    writer = tf.summary.FileWriter("logs/add_two_tensors", sess.graph)
    print(result)

12


In [66]:
tf.reset_default_graph()
with tf.variable_scope("multiplication"):
    A1 = tf.placeholder(dtype=tf.int32, name="A")
    B = tf.constant(5, name="B")
    C = tf.multiply(A1, B, name="C")
    D = tf.constant(10, name="D")
    E1 = tf.add(C, D, name="E")

print(E1)

Tensor("multiplication/E:0", dtype=int32)


In [67]:
with tf.variable_scope("division"):
    A2 = tf.placeholder(dtype=tf.int32, name="A")
    B = tf.constant(5, name="B")
    C = tf.floordiv(A2, B, name="C")
    D = tf.constant(10, name="D")
    E2 = tf.add(C, D, name="E")

print(E2)

Tensor("division/E:0", dtype=int32)


In [68]:
with tf.variable_scope("final"):
    with tf.Session() as sess:
        result = E1 + E2
        sess.run(result, feed_dict={A1: 2, A2: 10})
        tf.summary.FileWriter("logs/operations", sess.graph)

In [2]:
A = np.array([[1, 2], [3, 4]])

In [5]:
B = A.flatten()
print(B)

[1 2 3 4]


In [6]:
C = B.reshape(2, 2)
print(C)

[[1 2]
 [3 4]]


In [7]:
D = C.reshape(1, 4)
print(D)

[[1 2 3 4]]


In [8]:
E = D.reshape(4, 1)
E

array([[1],
       [2],
       [3],
       [4]])